/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

import logica.Cliente;
import logica.Concesionario;
import logica.Vehiculo;
import logica.Vendedor;
import logica.Venta;

/**
 *
 * @author brara
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    private Concesionario concesionario;
    private boolean calculado;
    private Vehiculo vehiculoActual;
    private Vehiculo[] dataVehiculo;
    private Vendedor[] dataVendedor;

    public vistaPrincipal() {
        initComponents();
        vehiculoActual = new Vehiculo();
        concesionario = new Concesionario();
        calculado = false;
        dataVehiculo = new Vehiculo[10];
        dataVendedor = new Vendedor[2];
        setLocationRelativeTo(null);

    }

    // Funcion para data de prueba
    private void dataTest() {
        for (int i = 0; i < dataVehiculo.length; i++) {
            dataVehiculo[i] = new Vehiculo();
        }

        for (int i = 0; i < dataVendedor.length; i++) {
            dataVendedor[i] = new Vendedor();
        }

        this.dataVendedor[0].setDni("1234");
        this.dataVendedor[0].setNombre("Bryan");
        this.dataVendedor[0].setDireccion("B");
        this.dataVendedor[0].setTelefono("g");

        this.dataVendedor[1].setDni("0987");
        this.dataVendedor[1].setNombre("BryanB");
        this.dataVendedor[1].setDireccion("B");
        this.dataVendedor[1].setTelefono("g");

        for (Vendedor vn : dataVendedor) {
            concesionario.agregarVendedor(vn);
        }

        this.dataVehiculo[0].setMatricula("AAA-123");
        this.dataVehiculo[1].setMatricula("AAA-234");
        this.dataVehiculo[2].setMatricula("AAA-345");
        this.dataVehiculo[3].setMatricula("AAA-456");
        this.dataVehiculo[4].setMatricula("AAA-567");
        this.dataVehiculo[5].setMatricula("AAA-678");
        this.dataVehiculo[6].setMatricula("AAA-789");
        this.dataVehiculo[7].setMatricula("AAA-890");
        this.dataVehiculo[8].setMatricula("AAA-321");
        this.dataVehiculo[9].setMatricula("AAA-432");
        this.dataVehiculo[0].setMarca("Mazda");
        this.dataVehiculo[1].setMarca("Toyota");
        this.dataVehiculo[2].setMarca("Ford");
        this.dataVehiculo[3].setMarca("Honda");
        this.dataVehiculo[4].setMarca("Honda");
        this.dataVehiculo[5].setMarca("Mazda");
        this.dataVehiculo[6].setMarca("Toyota");
        this.dataVehiculo[7].setMarca("Chevrolet");
        this.dataVehiculo[8].setMarca("Chevrolet");
        this.dataVehiculo[9].setMarca("Mercedez");
        this.dataVehiculo[0].setModelo("2012");
        this.dataVehiculo[1].setModelo("2013");
        this.dataVehiculo[2].setModelo("2014");
        this.dataVehiculo[3].setModelo("2015");
        this.dataVehiculo[4].setModelo("2016");
        this.dataVehiculo[5].setModelo("2017");
        this.dataVehiculo[6].setModelo("2018");
        this.dataVehiculo[7].setModelo("2019");
        this.dataVehiculo[8].setModelo("2011");
        this.dataVehiculo[9].setModelo("2010");
        this.dataVehiculo[0].setCilindrada("260");
        this.dataVehiculo[1].setCilindrada("260");
        this.dataVehiculo[2].setCilindrada("260");
        this.dataVehiculo[3].setCilindrada("260");
        this.dataVehiculo[4].setCilindrada("260");
        this.dataVehiculo[5].setCilindrada("260");
        this.dataVehiculo[6].setCilindrada("260");
        this.dataVehiculo[7].setCilindrada("260");
        this.dataVehiculo[8].setCilindrada("260");
        this.dataVehiculo[9].setCilindrada("260");
        this.dataVehiculo[0].setPrecio(120000000);
        this.dataVehiculo[1].setPrecio(130000000);
        this.dataVehiculo[2].setPrecio(140000000);
        this.dataVehiculo[3].setPrecio(150000000);
        this.dataVehiculo[4].setPrecio(10000000);
        this.dataVehiculo[5].setPrecio(180000000);
        this.dataVehiculo[6].setPrecio(150000000);
        this.dataVehiculo[7].setPrecio(250000000);
        this.dataVehiculo[8].setPrecio(120000000);
        this.dataVehiculo[9].setPrecio(150000000);

        for (Vehiculo vh : dataVehiculo) {
            concesionario.agregarVehiculo(vh);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConcesionaria = new javax.swing.JPanel();
        TabPanelConcesionaria = new javax.swing.JTabbedPane();
        panelAgregar = new javax.swing.JPanel();
        panelAgregarCliente = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        panelAgregarVehiculo = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCilindraje = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnAgregarVehiculo = new javax.swing.JButton();
        txtMatriculaLetras = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMatriculaNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblCantidadVehiculosRegistrados = new javax.swing.JLabel();
        panelVender = new javax.swing.JPanel();
        panelBuscarVehiculo = new javax.swing.JPanel();
        lblTituloBusvarVehiculo = new javax.swing.JLabel();
        txtLetrasMatricula = new javax.swing.JTextField();
        txtNumerosMatricula = new javax.swing.JTextField();
        btnBuscarMatricula = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelDatosVehiculo = new javax.swing.JPanel();
        btnVenderVehiculo = new javax.swing.JButton();
        panelOpcAdiconalesl1 = new javax.swing.JPanel();
        chckAireAcondicionado = new javax.swing.JCheckBox();
        chckMetalizado = new javax.swing.JCheckBox();
        btnCalcularPrecio = new javax.swing.JButton();
        scrollDatosVehiculo = new javax.swing.JScrollPane();
        panelDatosVehiculoScroll = new javax.swing.JPanel();
        lblDatosMatricula = new javax.swing.JLabel();
        lblDatosMarca = new javax.swing.JLabel();
        lblDatosModelo = new javax.swing.JLabel();
        lblDatosCilindrada = new javax.swing.JLabel();
        lblDatosPrecio = new javax.swing.JLabel();
        btnCederVehiculo = new javax.swing.JButton();
        panelDatosVenta = new javax.swing.JPanel();
        lblDniClienteVenta = new javax.swing.JLabel();
        txtDniClienteVenta = new javax.swing.JTextField();
        panelDatosVendedor = new javax.swing.JPanel();
        lblDniVendedorVenta = new javax.swing.JLabel();
        txtDniVendedorVenta = new javax.swing.JTextField();
        panelCederVehiculo = new javax.swing.JPanel();
        chckCederVehiculo = new javax.swing.JCheckBox();
        panelDatosVehiculoUsado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLetraMatriculaCeder = new javax.swing.JTextField();
        txtNumeroMatriculaCeder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMarcaCeder = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModeloCeder = new javax.swing.JTextField();
        txtCilindrajeCeder = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioCeder = new javax.swing.JTextField();
        panelBuscarVentas = new javax.swing.JPanel();
        panelBusquedaVentas = new javax.swing.JPanel();
        lblBuscarDniVendedor = new javax.swing.JLabel();
        btnBuscarVentas = new javax.swing.JButton();
        txtBuscarVentaCliente = new javax.swing.JTextField();
        scrollDatosVentas = new javax.swing.JScrollPane();
        panelDatosVentaBuscar = new javax.swing.JPanel();
        lblVentasDniCliente = new javax.swing.JLabel();
        lblVentasFechaVenta = new javax.swing.JLabel();
        lblVentasModelo = new javax.swing.JLabel();
        lblVentasOpcAdiconales = new javax.swing.JLabel();
        lblVentasNombreCliente = new javax.swing.JLabel();
        lblVentasNombreVendedor = new javax.swing.JLabel();
        lblVentasDniVendedor = new javax.swing.JLabel();
        lblVentasCesion = new javax.swing.JLabel();
        lblVentasUsado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAgregarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Nuevo Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblNombre.setText("Nombre:");

        lblDni.setText("DNI:");

        lblDireccion.setText("Dirección:");

        lblTelefono.setText("Telefono:");

        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarClienteLayout = new javax.swing.GroupLayout(panelAgregarCliente);
        panelAgregarCliente.setLayout(panelAgregarClienteLayout);
        panelAgregarClienteLayout.setHorizontalGroup(
            panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarClienteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtDni)
                    .addComponent(txtDireccion)
                    .addComponent(txtTelefono))
                .addGap(23, 23, 23))
            .addGroup(panelAgregarClienteLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnAgregarCliente)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        panelAgregarClienteLayout.setVerticalGroup(
            panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarClienteLayout.createSequentialGroup()
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarClienteLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCliente)
                .addContainerGap())
        );

        panelAgregarVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Nuevo Vehiculo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblMatricula.setText("Matricula:");

        lblMarca.setText("Marca:");

        lblModelo.setText("Modelo:");

        lblCilindraje.setText("Cilindraje:");

        lblPrecio.setText("Precio:");

        btnAgregarVehiculo.setText("Agregar");
        btnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVehiculoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("-");

        javax.swing.GroupLayout panelAgregarVehiculoLayout = new javax.swing.GroupLayout(panelAgregarVehiculo);
        panelAgregarVehiculo.setLayout(panelAgregarVehiculoLayout);
        panelAgregarVehiculoLayout.setHorizontalGroup(
            panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarVehiculoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAgregarVehiculoLayout.createSequentialGroup()
                        .addComponent(txtMatriculaLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatriculaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarVehiculo)
                .addGap(138, 138, 138))
        );
        panelAgregarVehiculoLayout.setVerticalGroup(
            panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarVehiculoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMatricula)
                    .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMatriculaNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatriculaLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCilindraje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnAgregarVehiculo)
                .addContainerGap())
        );

        lblCantidadVehiculosRegistrados.setText("Cantidad de Vehiculos registrados: 0/150");

        javax.swing.GroupLayout panelAgregarLayout = new javax.swing.GroupLayout(panelAgregar);
        panelAgregar.setLayout(panelAgregarLayout);
        panelAgregarLayout.setHorizontalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(panelAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidadVehiculosRegistrados)
                .addGap(74, 74, 74))
        );
        panelAgregarLayout.setVerticalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAgregarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadVehiculosRegistrados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabPanelConcesionaria.addTab("Agregar", panelAgregar);

        panelBuscarVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Vehiculo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblTituloBusvarVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloBusvarVehiculo.setText("Ingrese Matricula");

        btnBuscarMatricula.setText("Buscar");
        btnBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatriculaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("-");

        javax.swing.GroupLayout panelBuscarVehiculoLayout = new javax.swing.GroupLayout(panelBuscarVehiculo);
        panelBuscarVehiculo.setLayout(panelBuscarVehiculoLayout);
        panelBuscarVehiculoLayout.setHorizontalGroup(
            panelBuscarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloBusvarVehiculo)
                    .addGroup(panelBuscarVehiculoLayout.createSequentialGroup()
                        .addComponent(txtLetrasMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumerosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBuscarVehiculoLayout.setVerticalGroup(
            panelBuscarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBusvarVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLetrasMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumerosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMatricula)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelDatosVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculo"));

        btnVenderVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenderVehiculo.setText("Vender");
        btnVenderVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderVehiculoActionPerformed(evt);
            }
        });

        panelOpcAdiconalesl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones Adicionales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chckAireAcondicionado.setText("Aire Acondicionado");

        chckMetalizado.setText("Metalizado");

        btnCalcularPrecio.setText("Calcular Nuevo Precio");
        btnCalcularPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcAdiconalesl1Layout = new javax.swing.GroupLayout(panelOpcAdiconalesl1);
        panelOpcAdiconalesl1.setLayout(panelOpcAdiconalesl1Layout);
        panelOpcAdiconalesl1Layout.setHorizontalGroup(
            panelOpcAdiconalesl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcAdiconalesl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcAdiconalesl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckMetalizado)
                    .addComponent(chckAireAcondicionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcAdiconalesl1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnCalcularPrecio)
                .addGap(17, 17, 17))
        );
        panelOpcAdiconalesl1Layout.setVerticalGroup(
            panelOpcAdiconalesl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcAdiconalesl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckAireAcondicionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckMetalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnCalcularPrecio)
                .addContainerGap())
        );

        lblDatosMatricula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosMatricula.setText("Matricula: -");

        lblDatosMarca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosMarca.setText("Marca: -");

        lblDatosModelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosModelo.setText("Modelo: -");

        lblDatosCilindrada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosCilindrada.setText("CC: -");

        lblDatosPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosPrecio.setText("Precio: -");

        javax.swing.GroupLayout panelDatosVehiculoScrollLayout = new javax.swing.GroupLayout(panelDatosVehiculoScroll);
        panelDatosVehiculoScroll.setLayout(panelDatosVehiculoScrollLayout);
        panelDatosVehiculoScrollLayout.setHorizontalGroup(
            panelDatosVehiculoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosVehiculoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatosMatricula)
                    .addComponent(lblDatosMarca)
                    .addComponent(lblDatosModelo)
                    .addComponent(lblDatosCilindrada)
                    .addComponent(lblDatosPrecio))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        panelDatosVehiculoScrollLayout.setVerticalGroup(
            panelDatosVehiculoScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoScrollLayout.createSequentialGroup()
                .addComponent(lblDatosMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosCilindrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosPrecio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollDatosVehiculo.setViewportView(panelDatosVehiculoScroll);

        btnCederVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCederVehiculo.setText("Ceder");
        btnCederVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCederVehiculo.setEnabled(false);
        btnCederVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCederVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosVehiculoLayout = new javax.swing.GroupLayout(panelDatosVehiculo);
        panelDatosVehiculo.setLayout(panelDatosVehiculoLayout);
        panelDatosVehiculoLayout.setHorizontalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(scrollDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelOpcAdiconalesl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenderVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCederVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDatosVehiculoLayout.setVerticalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelOpcAdiconalesl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVenderVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCederVehiculo)
                        .addGap(36, 36, 36))
                    .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(scrollDatosVehiculo)))
                .addContainerGap())
        );

        panelDatosVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblDniClienteVenta.setText("DNI Cliente:");

        panelDatosVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Vendedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblDniVendedorVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDniVendedorVenta.setText("DNI Vendedor: ");

        javax.swing.GroupLayout panelDatosVendedorLayout = new javax.swing.GroupLayout(panelDatosVendedor);
        panelDatosVendedor.setLayout(panelDatosVendedorLayout);
        panelDatosVendedorLayout.setHorizontalGroup(
            panelDatosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDniVendedorVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniVendedorVenta)
                .addContainerGap())
        );
        panelDatosVendedorLayout.setVerticalGroup(
            panelDatosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVendedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDatosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDniVendedorVenta)
                    .addComponent(txtDniVendedorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDatosVentaLayout = new javax.swing.GroupLayout(panelDatosVenta);
        panelDatosVenta.setLayout(panelDatosVentaLayout);
        panelDatosVentaLayout.setHorizontalGroup(
            panelDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVentaLayout.createSequentialGroup()
                        .addComponent(lblDniClienteVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelDatosVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDatosVentaLayout.setVerticalGroup(
            panelDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDniClienteVenta)
                    .addComponent(txtDniClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatosVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCederVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ceder Vehiculo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chckCederVehiculo.setText("Ceder vehiculo usado");
        chckCederVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckCederVehiculoActionPerformed(evt);
            }
        });

        panelDatosVehiculoUsado.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculo Usado"));
        panelDatosVehiculoUsado.setEnabled(false);

        jLabel1.setText("Matricula: ");

        txtLetraMatriculaCeder.setEnabled(false);

        txtNumeroMatriculaCeder.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("-");

        jLabel3.setText("Marca:");

        txtMarcaCeder.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Cilindraje:");

        txtModeloCeder.setEnabled(false);

        txtCilindrajeCeder.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        jLabel8.setText("Precio:");

        txtPrecioCeder.setEnabled(false);

        javax.swing.GroupLayout panelDatosVehiculoUsadoLayout = new javax.swing.GroupLayout(panelDatosVehiculoUsado);
        panelDatosVehiculoUsado.setLayout(panelDatosVehiculoUsadoLayout);
        panelDatosVehiculoUsadoLayout.setHorizontalGroup(
            panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLetraMatriculaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroMatriculaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(txtMarcaCeder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtModeloCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCilindrajeCeder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        panelDatosVehiculoUsadoLayout.setVerticalGroup(
            panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                                .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtModeloCeder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCilindrajeCeder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoUsadoLayout.createSequentialGroup()
                                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtLetraMatriculaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNumeroMatriculaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtMarcaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosVehiculoUsadoLayout.createSequentialGroup()
                        .addGroup(panelDatosVehiculoUsadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioCeder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panelCederVehiculoLayout = new javax.swing.GroupLayout(panelCederVehiculo);
        panelCederVehiculo.setLayout(panelCederVehiculoLayout);
        panelCederVehiculoLayout.setHorizontalGroup(
            panelCederVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCederVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCederVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chckCederVehiculo)
                    .addComponent(panelDatosVehiculoUsado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        panelCederVehiculoLayout.setVerticalGroup(
            panelCederVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCederVehiculoLayout.createSequentialGroup()
                .addComponent(chckCederVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatosVehiculoUsado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVenderLayout = new javax.swing.GroupLayout(panelVender);
        panelVender.setLayout(panelVenderLayout);
        panelVenderLayout.setHorizontalGroup(
            panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCederVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVenderLayout.createSequentialGroup()
                        .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelBuscarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDatosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelVenderLayout.setVerticalGroup(
            panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVenderLayout.createSequentialGroup()
                        .addComponent(panelBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDatosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCederVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        TabPanelConcesionaria.addTab("Vender", panelVender);

        panelBusquedaVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblBuscarDniVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBuscarDniVendedor.setText("DNI Cliente");

        btnBuscarVentas.setText("Buscar");
        btnBuscarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaVentasLayout = new javax.swing.GroupLayout(panelBusquedaVentas);
        panelBusquedaVentas.setLayout(panelBusquedaVentasLayout);
        panelBusquedaVentasLayout.setHorizontalGroup(
            panelBusquedaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaVentasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelBusquedaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBuscarDniVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarVentaCliente)
                    .addComponent(btnBuscarVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        panelBusquedaVentasLayout.setVerticalGroup(
            panelBusquedaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaVentasLayout.createSequentialGroup()
                .addComponent(lblBuscarDniVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarVentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarVentas)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        scrollDatosVentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Venta"));

        lblVentasDniCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasDniCliente.setText("Dni Cliente: -");

        lblVentasFechaVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasFechaVenta.setText("Fecha venta: -");

        lblVentasModelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasModelo.setText("Modelo: -");

        lblVentasOpcAdiconales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasOpcAdiconales.setText("Opc Adicionales: -");

        lblVentasNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasNombreCliente.setText("Cliente: -");

        lblVentasNombreVendedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasNombreVendedor.setText("Vendedor: -");

        lblVentasDniVendedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasDniVendedor.setText("Dni Vendedor: -");

        lblVentasCesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasCesion.setText("Venta por Cesion: -");

        lblVentasUsado1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasUsado1.setText("Usado: -");

        javax.swing.GroupLayout panelDatosVentaBuscarLayout = new javax.swing.GroupLayout(panelDatosVentaBuscar);
        panelDatosVentaBuscar.setLayout(panelDatosVentaBuscarLayout);
        panelDatosVentaBuscarLayout.setHorizontalGroup(
            panelDatosVentaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentaBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosVentaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentasDniCliente)
                    .addComponent(lblVentasOpcAdiconales)
                    .addComponent(lblVentasModelo)
                    .addComponent(lblVentasFechaVenta)
                    .addComponent(lblVentasNombreCliente)
                    .addComponent(lblVentasDniVendedor)
                    .addComponent(lblVentasNombreVendedor)
                    .addComponent(lblVentasCesion)
                    .addComponent(lblVentasUsado1))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        panelDatosVentaBuscarLayout.setVerticalGroup(
            panelDatosVentaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentaBuscarLayout.createSequentialGroup()
                .addComponent(lblVentasDniCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasDniVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasNombreVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasFechaVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasOpcAdiconales)
                .addGap(18, 18, 18)
                .addComponent(lblVentasUsado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasCesion)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        lblVentasFechaVenta.getAccessibleContext().setAccessibleName("Fecha Venta: -");

        scrollDatosVentas.setViewportView(panelDatosVentaBuscar);

        javax.swing.GroupLayout panelBuscarVentasLayout = new javax.swing.GroupLayout(panelBuscarVentas);
        panelBuscarVentas.setLayout(panelBuscarVentasLayout);
        panelBuscarVentasLayout.setHorizontalGroup(
            panelBuscarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusquedaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDatosVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelBuscarVentasLayout.setVerticalGroup(
            panelBuscarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarVentasLayout.createSequentialGroup()
                .addComponent(panelBusquedaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(scrollDatosVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        TabPanelConcesionaria.addTab("Buscar Ventas", panelBuscarVentas);

        javax.swing.GroupLayout panelConcesionariaLayout = new javax.swing.GroupLayout(panelConcesionaria);
        panelConcesionaria.setLayout(panelConcesionariaLayout);
        panelConcesionariaLayout.setHorizontalGroup(
            panelConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConcesionariaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabPanelConcesionaria, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelConcesionariaLayout.setVerticalGroup(
            panelConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcesionariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanelConcesionaria)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConcesionaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConcesionaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasActionPerformed
        //Comprbamos que el campo no este vacio
        if (txtBuscarVentaCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes llenar el campo", "Buscar Venta",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dniCliente = txtBuscarVentaCliente.getText();
        String usado = "";

        //Buscamos el cliente dentro del registro de ventas
        Venta venta = concesionario.buscarVentaId(dniCliente);

        // si el resultado de la busqueda nos trae algo imprimimos en los label
        if (venta != null) {
            if (venta.getCedido()) {
                usado = "Si";
            }else{
                usado = "No";
            }

            lblVentasDniCliente.setText("DNI Cliente: " + venta.getCliente().getDni());
            lblVentasNombreCliente.setText("Cliente: " + venta.getCliente().getNombre());
            lblVentasDniVendedor.setText("DNI Vendedor: " + venta.getVendedor().getDni());
            lblVentasNombreVendedor.setText("Vendedor: " + venta.getVendedor().getNombre());
            lblVentasFechaVenta.setText("Fecha Venta: " + venta.getFecha());
            lblVentasModelo.setText("Modelo: " + venta.getVehiculo().getModelo());
            lblVentasCesion.setText("Usado: " + usado);
            //lblVentasDniCliente.setText("Opc Adicionales: " + venta.getCliente().getDni());

            txtBuscarVentaCliente.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "El DNI" + dniCliente + " No ha realizado ninguna compra", "Buscar Venta",
                JOptionPane.ERROR_MESSAGE);
            txtBuscarVentaCliente.setText("");
        }
    }//GEN-LAST:event_btnBuscarVentasActionPerformed

    private void chckCederVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckCederVehiculoActionPerformed
        boolean estado = chckCederVehiculo.isSelected();

        btnVenderVehiculo.setEnabled(!estado);
        btnCederVehiculo.setEnabled(estado);
        panelDatosVehiculoUsado.setEnabled(estado);
        txtLetraMatriculaCeder.setEnabled(estado);
        txtNumeroMatriculaCeder.setEnabled(estado);
        txtMarcaCeder.setEnabled(estado);
        txtModeloCeder.setEnabled(estado);
        txtPrecioCeder.setEnabled(estado);
        txtCilindrajeCeder.setEnabled(estado);
    }//GEN-LAST:event_chckCederVehiculoActionPerformed

    private void btnCederVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCederVehiculoActionPerformed
        //Verificamos que exista un vehiculo vigente pata vender
        if (vehiculoActual == null) {
            JOptionPane.showMessageDialog(null, "Aun no has buscado un vehiculo", "Vender Vehiculo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDniClienteVenta.getText().equals("") || txtDniVendedorVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dni de clientes y Vendedor deben llenarse", "Vender Vehiculo",
                JOptionPane.ERROR_MESSAGE);
        }

        //Taemos los datos de los campos de DNI de cliente y Vendedor
        String dniCliente = txtDniClienteVenta.getText();
        String dniVendedor = txtDniVendedorVenta.getText();

        //Traemos los datos del vehiculo que se cedera
        String matricula = txtLetraMatriculaCeder.getText() + "-" + txtNumeroMatriculaCeder.getText();
        String marca = txtMarcaCeder.getText();
        String modelo = txtModeloCeder.getText();
        int precio = Integer.parseInt(txtPrecioCeder.getText());
        String cilindraje = txtCilindrajeCeder.getText();

        //Buscamos a el Cliente y al Vendedor para Validar si existen
        Cliente cliente = concesionario.buscarCliente(dniCliente);
        Vendedor vendedor = concesionario.buscarVendedor(dniVendedor);

        //Primero verificamos que el precio
        if (precio <= vehiculoActual.getPrecio()) {
            JOptionPane.showMessageDialog(null, "El precio del vehiculo a ceder no puede ser menor al precio del vehiculo a comprar", "Vender Vehiculo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //verificamos que el cliente exista
        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cliente no existe", "Vender Vehiculo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //verificamos que el vendedor exista
        if (vendedor == null) {
            JOptionPane.showMessageDialog(null, "Vendedor no existe", "Vender Vehiculo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Construimos un nuevo vehiculo
        Vehiculo vehiculo = new Vehiculo(matricula, marca, modelo, cilindraje, precio);

        if (!concesionario.agregarVehiculo(vehiculo)) {
            JOptionPane.showMessageDialog(null, "Matricula del vehiculo ya existe", "Vender Vehiculo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Seteamos que el nuevo vehiculo es un vehiculo usado agregamos el nuevo vehiculo que ha sido cedido
        vehiculo.setUsado(true);
        concesionario.agregarVehiculo(vehiculo);

        //Seteamos que la venta fue por cesion de un vehiculo y creamos la nueva venta
        Venta venta = new Venta(cliente, vehiculoActual, vendedor);
        venta.setCedido(true);

        concesionario.agregarVenta(venta);

        //mensaje de confirmacion
        JOptionPane.showMessageDialog(null, "Vehiculo Vendido Correctamente", "Vender Nuevo Vehiculo", JOptionPane.INFORMATION_MESSAGE);

        //Limpieamos los campos una vez realizada la venta
        txtDniClienteVenta.setText("");
        txtDniVendedorVenta.setText("");
        txtNumerosMatricula.setText("");
        txtLetrasMatricula.setText("");
        chckAireAcondicionado.setSelected(false);
        chckMetalizado.setSelected(false);

        //limpiamos variables temporales
        calculado = false;
        vehiculoActual = null;

        //Limpiamos campos de label una vez la venta ha sido realizada
        this.lblDatosMatricula.setText("Matricula: -");
        this.lblDatosMarca.setText("Marca: -");
        this.lblDatosModelo.setText("Modelo: -");
        this.lblDatosCilindrada.setText("CC: -");
        this.lblDatosPrecio.setText("Precio: -");
    }//GEN-LAST:event_btnCederVehiculoActionPerformed

    private void btnCalcularPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPrecioActionPerformed
        int precio = vehiculoActual.getPrecio(); //se trae el vehiculo que dio resultado en la busqueda y trabajar con el
        if (calculado) {
            JOptionPane.showMessageDialog(null, "Ya el precio ha sido calculado", "Calcular adicionales",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        //si el check button esta seleccionado, se le aumenta el precio
        if (this.chckAireAcondicionado.isSelected()) {
            vehiculoActual.setPrecio(precio += 500000);
            calculado = true; // se actualiza la bandera para que no sea calculado mas de una vez
        }

        //Si el check button esta seleccionado, se le aumenta el precio
        if (this.chckMetalizado.isSelected()) {
            vehiculoActual.setPrecio(precio += 800000);
            calculado = true; //Se actualiza la bandera para que no calcule mas de una vez
        }

        this.lblDatosPrecio.setText("Precio: " + concesionario.formatoValor(vehiculoActual.getPrecio()));
    }//GEN-LAST:event_btnCalcularPrecioActionPerformed

    private void btnVenderVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderVehiculoActionPerformed
        //Verificamos que exista un vehiculo vigente pata vender
        if (vehiculoActual == null) {
            JOptionPane.showMessageDialog(null, "Aun no has buscado un vehiculo", "Vender Vehiculo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDniClienteVenta.getText().equals("") || txtDniVendedorVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dni de clientes y Vendedor deben llenarse", "Vender Vehiculo",
                JOptionPane.ERROR_MESSAGE);
        }

        String dniCliente = txtDniClienteVenta.getText();
        String dniVendedor = txtDniVendedorVenta.getText();

        Cliente cliente = concesionario.buscarCliente(dniCliente);
        Vendedor vendedor = concesionario.buscarVendedor(dniVendedor);

        if (cliente != null) {
            if (vendedor != null) {
                Venta venta = new Venta(cliente, vehiculoActual, vendedor);

                concesionario.agregarVenta(venta);
                calculado = false;
                vehiculoActual = null;
                JOptionPane.showMessageDialog(null, "Vehiculo Vendido Correctamente", "Vender Nuevo Vehiculo",
                    JOptionPane.INFORMATION_MESSAGE);
                //Limpieamos los campos una vez realizada la venta
                txtDniClienteVenta.setText("");
                txtDniVendedorVenta.setText("");
                txtNumerosMatricula.setText("");
                txtLetrasMatricula.setText("");
                chckAireAcondicionado.setSelected(false);
                chckMetalizado.setSelected(false);

            } else {
                JOptionPane.showMessageDialog(null, "Vendedor no existe", "Vender Vehiculo",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cliente no existe", "Vender Vehiculo",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVenderVehiculoActionPerformed

    private void btnBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaActionPerformed
        // Se Verifica que los campos esten vacios para evitar enviar datos vacios
        if (txtLetrasMatricula.getText().equals("") || txtNumerosMatricula.getText().equals("")) {
            return;
        }

        // Se obtiene los datos del campo y se guardan en una variable para mejor manejo
        String matricula = txtLetrasMatricula.getText() + "-" + txtNumerosMatricula.getText();

        Vehiculo vehiculo = concesionario.buscarVehiculo(matricula);

        if (vehiculo != null) {
            this.lblDatosMatricula.setText("Matricula: " + vehiculo.getMatricula());
            this.lblDatosMarca.setText("Marca: " + vehiculo.getMarca());
            this.lblDatosModelo.setText("Modelo: " + vehiculo.getModelo());
            this.lblDatosCilindrada.setText("CC: " + vehiculo.getCilindrada());
            this.lblDatosPrecio.setText("Precio: " + concesionario.formatoValor(vehiculo.getPrecio()));
            this.vehiculoActual = vehiculo; // se Guarda en una variable global el vehiculo actual para operarlo despues
        } else {
            JOptionPane.showMessageDialog(null, "Matricula no encontrada", "Buscar Matricula",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarMatriculaActionPerformed

    private void btnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoActionPerformed
        // Condicional para evitar que el codigo se ejecite con los campos vacios
        if (txtMatriculaLetras.getText().equals("") || txtMatriculaNumero.getText().equals("")
            || txtMarca.getText().equals("") || txtModelo.getText().equals("")
            || txtCilindraje.getText().equals("") || txtPrecio.getText().equals("")) {
            dataTest(); // Agregar data de prueba
            return;
        }

        // Se obtienen todos los datos de cada campo y se guardan en variables para
        // mejor manejo
        String matricula = txtMatriculaLetras.getText() + "-" + txtMatriculaNumero.getText();
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String cilindraje = txtCilindraje.getText();
        int precio = Integer.parseInt(txtPrecio.getText()); // Se convierte el valor del campo en un integer para operar
        // con el
        // Se construye un objeto de tipo vehiculo para proceder a guardar
        Vehiculo vehiculo = new Vehiculo(matricula, marca, modelo, cilindraje, precio);

        if (concesionario.agregarVehiculo(vehiculo)) { // comparar si el buscador guardo correctamente
            JOptionPane.showMessageDialog(null, "Vehiculo agregado Correctamente", "Agregar Nuevo Vehiculo",
                JOptionPane.INFORMATION_MESSAGE);

            // Se manda un mensaje de confirmacion que ya se ha guardado
            // Se limpian los campos del formulario
            txtMatriculaLetras.setText("");
            txtMatriculaNumero.setText("");
            txtMarca.setText("");
            txtModelo.setText("");
            txtCilindraje.setText("");
            txtPrecio.setText("");
            this.lblCantidadVehiculosRegistrados
            .setText("Cantidad de Vehiculos registrados: " + concesionario.getIndiceVehiculo() + "/150");
        } else {
            // Si ocurrio algun error, se manda un mensaje de error
            JOptionPane.showMessageDialog(null, "Vehiculo ya existe.", "Vehiculo nuevo Cliente.",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarVehiculoActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // Condicional para evitar que el codigo se ejecite con los campos vacios
        if (txtNombre.getText().equals("") || txtDni.getText().equals("") || txtDireccion.getText().equals("")
            || txtTelefono.getText().equals("")) {
            return;
        }

        // Se obtienen todos los datos de cada campo y se guardan en variables para
        // mejor manejo
        String nombre = txtNombre.getText();
        String dni = txtDni.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();

        // Se construye un objeto de tipo vehiculo para proceder a guardar
        Cliente cliente = new Cliente(nombre, dni, direccion, telefono);

        if (concesionario.agregarCliente(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente agregado Correctamente", "Agregar Nuevo Cliente",
                JOptionPane.INFORMATION_MESSAGE);
            // Se manda un mensaje de confirmacion que ya se ha guardado
            // Se limpian los campos del formulario
            txtNombre.setText("");
            txtDni.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
        } else {
            // Si ocurrio algun error, se manda un mensaje de error
            JOptionPane.showMessageDialog(null, "Cliente ya existe.", "Agregar nuevo Cliente.",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPanelConcesionaria;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarVehiculo;
    private javax.swing.JButton btnBuscarMatricula;
    private javax.swing.JButton btnBuscarVentas;
    private javax.swing.JButton btnCalcularPrecio;
    private javax.swing.JButton btnCederVehiculo;
    private javax.swing.JButton btnVenderVehiculo;
    private javax.swing.JCheckBox chckAireAcondicionado;
    private javax.swing.JCheckBox chckCederVehiculo;
    private javax.swing.JCheckBox chckMetalizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBuscarDniVendedor;
    private javax.swing.JLabel lblCantidadVehiculosRegistrados;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblDatosCilindrada;
    private javax.swing.JLabel lblDatosMarca;
    private javax.swing.JLabel lblDatosMatricula;
    private javax.swing.JLabel lblDatosModelo;
    private javax.swing.JLabel lblDatosPrecio;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDniClienteVenta;
    private javax.swing.JLabel lblDniVendedorVenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloBusvarVehiculo;
    private javax.swing.JLabel lblVentasCesion;
    private javax.swing.JLabel lblVentasDniCliente;
    private javax.swing.JLabel lblVentasDniVendedor;
    private javax.swing.JLabel lblVentasFechaVenta;
    private javax.swing.JLabel lblVentasModelo;
    private javax.swing.JLabel lblVentasNombreCliente;
    private javax.swing.JLabel lblVentasNombreVendedor;
    private javax.swing.JLabel lblVentasOpcAdiconales;
    private javax.swing.JLabel lblVentasUsado1;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelAgregarCliente;
    private javax.swing.JPanel panelAgregarVehiculo;
    private javax.swing.JPanel panelBuscarVehiculo;
    private javax.swing.JPanel panelBuscarVentas;
    private javax.swing.JPanel panelBusquedaVentas;
    private javax.swing.JPanel panelCederVehiculo;
    private javax.swing.JPanel panelConcesionaria;
    private javax.swing.JPanel panelDatosVehiculo;
    private javax.swing.JPanel panelDatosVehiculoScroll;
    private javax.swing.JPanel panelDatosVehiculoUsado;
    private javax.swing.JPanel panelDatosVendedor;
    private javax.swing.JPanel panelDatosVenta;
    private javax.swing.JPanel panelDatosVentaBuscar;
    private javax.swing.JPanel panelOpcAdiconalesl1;
    private javax.swing.JPanel panelVender;
    private javax.swing.JScrollPane scrollDatosVehiculo;
    private javax.swing.JScrollPane scrollDatosVentas;
    private javax.swing.JTextField txtBuscarVentaCliente;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtCilindrajeCeder;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniClienteVenta;
    private javax.swing.JTextField txtDniVendedorVenta;
    private javax.swing.JTextField txtLetraMatriculaCeder;
    private javax.swing.JTextField txtLetrasMatricula;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarcaCeder;
    private javax.swing.JTextField txtMatriculaLetras;
    private javax.swing.JTextField txtMatriculaNumero;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModeloCeder;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroMatriculaCeder;
    private javax.swing.JTextField txtNumerosMatricula;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioCeder;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
